import mongoose from "mongoose";

const normalizeIndianPhoneNumber = (value) => {
  if (typeof value !== "string") return undefined;

  const trimmed = value.trim();
  if (!trimmed) return undefined;

  const digitsOnly = trimmed.replace(/\D/g, "");

  if (digitsOnly.length === 10) {
    return `+91${digitsOnly}`;
  }

  if (digitsOnly.length === 12 && digitsOnly.startsWith("91")) {
    return `+${digitsOnly}`;
  }

  if (trimmed.startsWith("+91") && digitsOnly.length === 12 && digitsOnly.startsWith("91")) {
    return `+${digitsOnly}`;
  }

  return trimmed;
};

const userSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
    },
    fullName: {
      type: String,
      required: true,
    },
    username: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
      lowercase: true,
      alias: "handle",
      minlength: 3,
      maxlength: 30,
      match: /^[a-z0-9_.]+$/,
      index: true,
    },
    usernameAutoGenerated: {
      type: Boolean,
      default: false,
    },
    password: {
      type: String,
      required: true,
      minlength: 12,
    },
    profilePic: {
      type: String,
      default: "",
    },
    lastSeen: {
      type: Date,
      default: null,
    },
    phoneNumber: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
      alias: "phone",
      set: normalizeIndianPhoneNumber,
      match: /^\+91\d{10}$/,
      index: true,
    },
    isPhoneVerified: {
      type: Boolean,
      default: false,
    },
    tokenVersion: {
      type: Number,
      default: 0,
    },
    refreshTokenHash: {
      type: String,
      default: "",
    },
    refreshTokenExpiresAt: {
      type: Date,
      default: null,
    },
    refreshSessions: [
      {
        tokenId: { type: String, required: true },
        tokenHash: { type: String, required: true },
        createdAt: { type: Date, default: Date.now },
        expiresAt: { type: Date, required: true },
        revokedAt: { type: Date, default: null },
        replacedByTokenId: { type: String, default: null },
        ip: { type: String, default: "" },
        userAgent: { type: String, default: "" },
      },
    ],
    blockedUsers: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],
  },
  { timestamps: true } //shows creaatedAt and updatedAt automatically
);

const User = mongoose.model("User", userSchema);

export default User;
