apiVersion: v1
kind: ConfigMap
metadata:
  name: linepe-config
  namespace: linepe
data:
  NODE_ENV: "production"
  PORT: "5000"
  CLIENT_URL: "https://line-pe.vercel.app"
  CLIENT_URLS: "https://line-pe.vercel.app"
  COOKIE_SAME_SITE: "none"
  COOKIE_SECURE: "true"
  REDIS_URL: "redis://redis:6379"
  INVITE_BASE_URL: "https://line-pe.vercel.app"
