apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linepe
  namespace: linepe
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: linepe.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linepe
                port:
                  number: 80
