import { Pool } from "pg";

import { logger } from "./logger.js";

let pool;
let schemaReadyPromise = null;

const getConnectionString = () =>
  process.env.POSTGRES_URL ||
  process.env.POSTGRES_URI ||
  process.env.DATABASE_URL ||
  "";

export const getPostgresPool = () => {
  if (pool) return pool;

  const connectionString = getConnectionString();
  if (!connectionString) {
    throw new Error("Missing PostgreSQL connection string (set POSTGRES_URL, POSTGRES_URI, or DATABASE_URL)");
  }

  pool = new Pool({
    connectionString,
    ssl: process.env.POSTGRES_SSL === "true" ? { rejectUnauthorized: false } : undefined,
  });

  return pool;
};

const ensureRegisteredUsersTable = async () => {
  const client = await getPostgresPool().connect();

  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS registered_users (
        id BIGSERIAL PRIMARY KEY,
        mongo_user_id TEXT NOT NULL UNIQUE,
        email TEXT NOT NULL UNIQUE,
        full_name TEXT NOT NULL,
        username TEXT NOT NULL UNIQUE,
        username_auto_generated BOOLEAN NOT NULL DEFAULT FALSE,
        profile_pic TEXT NOT NULL DEFAULT '',
        phone_number TEXT UNIQUE,
        is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
        last_seen TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
  } finally {
    client.release();
  }
};

export const connectPostgres = async () => {
  try {
    const nextPool = getPostgresPool();
    const client = await nextPool.connect();
    client.release();

    if (!schemaReadyPromise) {
      schemaReadyPromise = ensureRegisteredUsersTable();
    }
    await schemaReadyPromise;

    logger.info("db.postgres.connected");
  } catch (error) {
    logger.error("db.postgres.connection_failed", { error });
  }
};

export const upsertRegisteredUser = async (user) => {
  if (!user?._id) return;

  if (!schemaReadyPromise) {
    schemaReadyPromise = ensureRegisteredUsersTable();
  }
  await schemaReadyPromise;

  await getPostgresPool().query(
    `
      INSERT INTO registered_users (
        mongo_user_id,
        email,
        full_name,
        username,
        username_auto_generated,
        profile_pic,
        phone_number,
        is_phone_verified,
        last_seen,
        created_at,
        updated_at
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11
      )
      ON CONFLICT (mongo_user_id) DO UPDATE SET
        email = EXCLUDED.email,
        full_name = EXCLUDED.full_name,
        username = EXCLUDED.username,
        username_auto_generated = EXCLUDED.username_auto_generated,
        profile_pic = EXCLUDED.profile_pic,
        phone_number = EXCLUDED.phone_number,
        is_phone_verified = EXCLUDED.is_phone_verified,
        last_seen = EXCLUDED.last_seen,
        created_at = EXCLUDED.created_at,
        updated_at = EXCLUDED.updated_at
    `,
    [
      String(user._id),
      user.email || "",
      user.fullName || "",
      user.username || "",
      Boolean(user.usernameAutoGenerated),
      user.profilePic || "",
      user.phoneNumber || null,
      Boolean(user.isPhoneVerified),
      user.lastSeen || null,
      user.createdAt || new Date(),
      user.updatedAt || new Date(),
    ]
  );
};
