import Link from "next/link";
import { redirect } from "next/navigation";

import { getAuthSession } from "@/lib/server-auth";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Profile",
  robots: {
    index: false,
    follow: false,
  },
};

const formatDate = (value) => {
  if (!value) {
    return "Not available";
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "Not available";
  }

  return new Intl.DateTimeFormat("en", {
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(date);
};

const initialsFromUser = (user) => {
  const name = user.fullName || user.username || user.email || "LinePe";

  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0])
    .join("")
    .toUpperCase();
};

function StatusBadge({ verified }) {
  return (
    <span
      className={`inline-flex rounded-md px-2.5 py-1 text-xs font-bold ${
        verified
          ? "bg-emerald-100 text-emerald-700"
          : "bg-amber-100 text-amber-800"
      }`}
    >
      {verified ? "Verified" : "Not verified"}
    </span>
  );
}

function Field({ label, value, children }) {
  return (
    <div className="border-b border-stone-200 py-5 last:border-b-0">
      <dt className="text-xs font-bold uppercase text-stone-500">{label}</dt>
      <dd className="mt-2 text-sm font-semibold text-stone-950">
        {children || value || "Not available"}
      </dd>
    </div>
  );
}

export default async function ProfilePage() {
  const { user, canRefresh } = await getAuthSession();

  if (!user) {
    if (canRefresh) {
      redirect("/api/auth/refresh-session?next=/profile");
    }

    redirect("/login?next=/profile");
  }

  return (
    <main className="min-h-screen bg-[#f4f6f2] text-stone-950">
      <header className="border-b border-stone-200 bg-white">
        <nav className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-5 sm:px-6">
          <Link href="/" className="flex items-center gap-3" aria-label="LinePe home">
            <span className="flex size-9 items-center justify-center rounded-md bg-emerald-600 text-sm font-bold text-white">
              L
            </span>
            <span className="text-lg font-bold">LinePe</span>
          </Link>

          <div className="flex items-center gap-2">
            <Link
              href="/chat"
              className="rounded-md px-3 py-2 text-sm font-semibold text-stone-600 hover:bg-stone-100 hover:text-stone-950"
            >
              Chat
            </Link>
            <Link
              href="/settings"
              className="rounded-md bg-stone-950 px-4 py-2 text-sm font-semibold text-white hover:bg-stone-800"
            >
              Settings
            </Link>
          </div>
        </nav>
      </header>

      <section className="mx-auto grid w-full max-w-6xl gap-6 px-5 py-8 sm:px-6 lg:grid-cols-[340px_1fr]">
        <aside className="rounded-lg border border-stone-200 bg-white p-6">
          <div className="flex flex-col items-center text-center">
            <div className="flex size-24 items-center justify-center rounded-lg bg-emerald-600 text-3xl font-black text-white">
              {initialsFromUser(user)}
            </div>
            <h1 className="mt-5 text-2xl font-black text-stone-950">
              {user.fullName || "LinePe user"}
            </h1>
            <p className="mt-2 max-w-full truncate text-sm font-semibold text-stone-500">
              {user.username ? `@${user.username}` : user.email}
            </p>
          </div>

          <div className="mt-6 border-t border-stone-200 pt-5">
            <div className="flex items-center justify-between gap-4">
              <span className="text-sm font-bold text-stone-700">Account status</span>
              <span className="rounded-md bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-700">
                Active
              </span>
            </div>
            <div className="mt-5">
              <p className="text-xs font-bold uppercase text-stone-500">Member since</p>
              <p className="mt-2 text-sm font-semibold text-stone-950">
                {formatDate(user.createdAt)}
              </p>
            </div>
          </div>
        </aside>

        <section className="rounded-lg border border-stone-200 bg-white">
          <div className="border-b border-stone-200 px-6 py-5">
            <p className="text-sm font-bold uppercase text-emerald-700">Profile</p>
            <h2 className="mt-2 text-2xl font-black text-stone-950">
              Your profile information
            </h2>
          </div>

          <dl className="px-6">
            <Field label="Full name" value={user.fullName} />
            <Field label="Username">
              <span>{user.username || "Not available"}</span>
              {user.usernameAutoGenerated ? (
                <span className="ml-3 rounded-md bg-amber-100 px-2 py-0.5 text-xs font-bold text-amber-800">
                  Auto-generated
                </span>
              ) : null}
            </Field>
            <Field label="Email address">
              <span className="mr-3">{user.email}</span>
              <StatusBadge verified={user.isEmailVerified} />
            </Field>
            <Field label="Phone number">
              <span className="mr-3">{user.phoneNumber || "Not available"}</span>
              {user.phoneNumber ? (
                <StatusBadge verified={user.isPhoneVerified} />
              ) : null}
            </Field>
            <Field label="Last updated" value={formatDate(user.updatedAt)} />
          </dl>
        </section>
      </section>
    </main>
  );
}
