import bcrypt from "bcryptjs";
import dotenv from "dotenv";

import { connectDB } from "../lib/db.js";
import User from "../models/user.model.js";

dotenv.config();

const admin = {
  email: "admin070801@gmail.com",
  fullName: "LinePe Admin",
  username: "admin070801",
  password: "S@natanmomo071201",
};

const run = async () => {
  await connectDB();

  const hashedPassword = await bcrypt.hash(admin.password, 10);
  const user = await User.findOneAndUpdate(
    { email: admin.email },
    {
      $set: {
        fullName: admin.fullName,
        username: admin.username,
        usernameAutoGenerated: false,
        password: hashedPassword,
      },
    },
    {
      new: true,
      upsert: true,
      setDefaultsOnInsert: true,
    }
  );

  console.log(`Admin user ready: ${user.email} (${user.username})`);
  process.exit(0);
};

run().catch((error) => {
  console.error("Failed to seed admin user:", error);
  process.exit(1);
});
