import { cookies } from "next/headers";

const AUTH_COOKIE_NAMES = new Set(["accessToken", "refreshToken"]);

export const getApiBaseUrl = () => {
  const explicitBaseUrl = process.env.BACKEND_API_URL;

  if (explicitBaseUrl) {
    return explicitBaseUrl.replace(/\/+$/, "");
  }

  const origin = (process.env.NEXT_PUBLIC_API_ORIGIN || "http://localhost:5000").replace(/\/+$/, "");
  return origin.endsWith("/api") ? origin : `${origin}/api`;
};

export const buildAuthCookieHeader = async () => {
  const cookieStore = await cookies();
  const authCookies = cookieStore
    .getAll()
    .filter((cookie) => AUTH_COOKIE_NAMES.has(cookie.name));

  if (authCookies.length === 0) {
    return "";
  }

  return authCookies
    .map((cookie) => `${cookie.name}=${encodeURIComponent(cookie.value)}`)
    .join("; ");
};

const serializeUser = (user) => ({
  _id: String(user?._id || ""),
  fullName: user?.fullName || "",
  email: user?.email || "",
  username: user?.username || "",
  usernameAutoGenerated: Boolean(user?.usernameAutoGenerated),
  phoneNumber: user?.phoneNumber || "",
  isPhoneVerified: Boolean(user?.isPhoneVerified),
  profilePic: user?.profilePic || "",
  isEmailVerified: Boolean(user?.isEmailVerified),
  createdAt: user?.createdAt || null,
  updatedAt: user?.updatedAt || null,
});

export async function getAuthSession() {
  const cookieHeader = await buildAuthCookieHeader();
  const hasAccessToken = cookieHeader.includes("accessToken=");
  const hasRefreshToken = cookieHeader.includes("refreshToken=");

  if (!hasAccessToken) {
    return {
      user: null,
      canRefresh: hasRefreshToken,
    };
  }

  try {
    const response = await fetch(`${getApiBaseUrl()}/auth/check`, {
      cache: "no-store",
      headers: {
        Accept: "application/json",
        Cookie: cookieHeader,
      },
    });

    if (!response.ok) {
      return {
        user: null,
        canRefresh: hasRefreshToken,
      };
    }

    return {
      user: serializeUser(await response.json()),
      canRefresh: false,
    };
  } catch {
    return {
      user: null,
      canRefresh: hasRefreshToken,
    };
  }
}

export async function getCurrentUser() {
  const session = await getAuthSession();
  return session.user;
}
